### ISSUE TITLE
 => ERROR [6/6] RUN python code-fix.py     

### ISSUE THREAD

**Issue by ucas010** [soulteary/docker-codeformer#1]
0.185 Traceback (most recent call last):                                                                            
0.185   File "code-fix.py", line 27, in <module>                                                                    
0.185     save_file(basicsr_utils_misc, fix_version_check(read_file(basicsr_utils_misc)))                           
0.185   File "code-fix.py", line 4, in read_file                                                                    
0.185     file = open(filepath, "r")
0.185 FileNotFoundError: [Errno 2] No such file or directory: 'basicsr/utils/misc.py'

**Comment by ucas010** [comment]
Traceback (most recent call last):
  File "app.py", line 11, in <module>
    from basicsr.archs.rrdbnet_arch import RRDBNet
ModuleNotFoundError: No module named 'basicsr'
这个执行环境和位置在哪啊？
我能不能自己安装一下解决？
